# Generated by Django 4.2.5 on 2024-04-14 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0002_order_pricepolicy_transactionrecord"),
    ]

    operations = [
        migrations.AlterField(
            model_name="level",
            name="percent",
            field=models.IntegerField(
                help_text="填入0-100整数表示百分比，例如：90，表示90%", verbose_name="折扣"
            ),
        ),
    ]
